# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    # -   id: check-yaml
    # -   id: check-added-large-files
# -   repo: https://github.com/pre-commit/mirrors-autopep8
#     rev: 'v1.5'  # Use the sha / tag you want to point at
#     hooks:
#     -   id: autopep8
# -   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
# -   repo: https://github.com/PyCQA/flake8
#     rev: 3.7.8
#     hooks:
#     -   id: flake8
#         language_version: python3
# -   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
#     rev: v1.0.3
#     hooks:
#     -   id: python-bandit-vulnerability-check
#         args: [-l, --recursive, -x, tests]
#         files: .py$
# -   repo: https://github.com/asottile/pyupgrade
#     rev: v1.25.1
#     hooks:
#     -   id: pyupgrade
# -   repo: local
#     hooks:
#     -   id: tests
#         name: run tests
#         entry: python -m pytest -v
#         pass_filenames: false
#         language: system
#         types: [python]
#         stages: [commit]
